### PR TITLE
Inserted .DS_Store in .gitignore for those programing on the Mac

### PR DESCRIPTION
**Pull request by Tokuriku**

### CODE REVIEW

**Comment by phantomwhale** [comment]
Can you remove the upstream merge from the commit (it's not necessary). For cleanness, you might want to chuck away the revert and revert revert from your local branch using `git reset --hard e8d8615` too (although only if you've not committed anything else to the branch yet, otherwise this will remove that as well !)

**Comment by Tokuriku** [comment]
I have brought back my local branch to just before the merge thanks to your help.
(I've been at this for the past 3 hours...)
The software doesn't permit me to push as is because it would change the history of my remote branch on GitHub.
How can I solve this?

**Comment by Tokuriku** [comment]
Also, how do I remove the upstream merge from the commit?

**Comment by phantomwhale** [comment]
Add a `-f` flag to your push, e.g. `git push origin master -f`

Explained quite well here : http://christoph.ruegg.name/blog/2010/5/5/git-howto-revert-a-commit-already-pushed-to-a-remote-reposit.html

**Comment by phantomwhale** [comment]
Not sure how to adjust the pull request commit range. There is a control somewhere. You may need to feed it the name of your first commit, which was `a16fc40b97b3981c60bd7c43c5f45d0bd8ead728`. Its new to me, so might need to hunt around the github interface a little. The github help pages are normally pretty good too.

**Comment by Tokuriku** [comment]
Got all under control on this end.
I'll send a new merge request with only my .DS_Store commit.
I'll merge afterwards and see next time how to send a pull request without the merge.

**Comment by Tokuriku** [comment]
Seems that the original Pull Request was updated when I pushed from local!!!

**Pull request merged**
